Add dev.sh to avoid setting GEM_HOME and GEM_PATH
postmodern/chruby pull request #487
Opened 2023-01-18 06:59 UTC by k0kubun

Closes #422

I added `dev.sh` file as per https://github.com/postmodern/chruby/issues/422#issuecomment-1292899140.

2023-01-19 00:47 UTC, postmodern requested changes
Spotted a bug on line 59. I also do not think `dev.sh` is necessary if it only sets a global variable.

Also, I am hesitant about adding more global variables. I think hook functions might be a better option. I may try to make a separate branch of the 0.4.0 branch to demonstrate the idea of extracting the `GEM_HOME`/`GEM_PATH` logic into a hook function that can be overrode.

2023-01-19 07:23 UTC, k0kubun commented on share/chruby/dev.sh
> +export CHRUBY_DEV=1
Do you mean something like this? https://github.com/postmodern/chruby/pull/487/commits/db6f6035d822fa406c9242cdd2533140ae28b42f

2023-01-19 07:23 UTC, k0kubun commented on share/chruby/chruby.sh
>  		export PATH="$GEM_HOME/bin:$PATH"
Thanks for catching it. Addressed in https://github.com/postmodern/chruby/pull/487/commits/db6f6035d822fa406c9242cdd2533140ae28b42f.

2023-01-19 08:46 UTC, postmodern commented on share/chruby/dev.sh
> +export CHRUBY_DEV=1
Excellent. Looks good.

2023-01-19 08:51 UTC, postmodern requested changes
Now this obviously needs tests. The unit tests are located in the `test/unit/` directory and use [shunit2](https://github.com/kward/shunit2#readme) which you should be able to install via your system's package manager (`brew install shunit2` or `sudo apt install -y shunit2`). You can probably copy the existing tests from [`test/unit/chruby_use_test.sh`](https://github.com/postmodern/chruby/blob/master/test/unit/chruby_use_test.sh) but test that `GEM_HOME` and `GEM_PATH` do not get set. The test files can be ran locally by simply executing the file, since the `*_test.s` files are just shell scripts.

2023-01-20 07:55 UTC, k0kubun commented
Thanks for the advice. I copied `test/unit/chruby_use_test.sh` to `test/unit/chruby_dev_test.sh` and modified it for the changed behavior. I'd appreciate another look when you have a chance.

2023-01-20 10:16 UTC, postmodern commented
The tests all passed! I will have to manually merge this into the 0.4.0 branch. Then I will have to start working on release engineering and preparing a 0.4.0 release. I may also need to do a 0.3.9 release since the `main` branch contains a fix for detecting `mruby` ruby versions.

2023-01-21 06:26 UTC, postmodern commented
Manually merged into [0.4.0](https://github.com/postmodern/chruby/tree/0.4.0).

2023-01-21 06:26 UTC, closed without merging